package org.vrml.lsp.spec;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * The shipped table, pinned node by node.
 *
 * <p>{@link Spec} is generated by joining three sources with regular expressions and a
 * StAX parser, and both failure modes are silent: a regex that stops matching drops a field
 * without anybody noticing, and a join that misses keeps the field but empties its type or
 * default. So three real nodes are quoted here character for character - the narrowest
 * ({@code Coordinate}, one field), the widest ({@code IndexedFaceSet}, twenty, with node
 * references, eventIns and plain fields at once) and one with a {@code MFString} plus a nested
 * {@code SFNode} ({@code Text}). Anything that changes what the generator extracts from
 * {@code Base*.java} or from UOM has to change one of these lines first.
 *
 * <p>These read the real resource from the jar, not a fixture, so they also prove the file was
 * built and copied before the tests ran.
 */
class SpecTest {

    private static Spec spec;

    @BeforeAll
    static void loadTheShippedTable() {
        spec = Spec.load();
    }

    /** {@code name:type:access}, the triple the extractor is supposed to get right. */
    private static List<String> shape(Spec.Node node) {
        List<String> out = new ArrayList<>();
        for (Spec.Field field : node.fields()) {
            out.add(field.name() + ":" + field.type() + ":" + field.access());
        }
        return out;
    }

    private static Spec.Node node(String name) {
        Spec.Node found = spec.node(name).orElse(null);
        assertTrue(found != null, "the table has no node " + name);
        return found;
    }

    @Test
    void everyProfileNodeHasFields() {
        assertEquals(56, spec.nodes().size(), "profiles.xml lists 56 VRML97 nodes");
        List<String> empty = new ArrayList<>();
        for (Spec.Node node : spec.nodes()) {
            if (node.fields().isEmpty()) {
                empty.add(node.name());
            }
        }
        assertEquals(List.of(), empty, "a node with no fields cannot be completed or validated");
    }

    @Test
    void coordinateIsTheNarrowestNode() {
        Spec.Node coordinate = node("Coordinate");
        assertEquals("Rendering", coordinate.component());
        assertEquals(1, coordinate.level());
        assertEquals(List.of("point:MFVec3f:exposedField"), shape(coordinate));
        // UOM writes no `default` for a multi-value field, because "no values" is its default; an
        // empty string here means exactly that, not "the join found nothing".
        assertEquals("", field(coordinate, "point").defaultValue());
        assertEquals("point contains a set of 3D coordinate (triplet) point values.",
                field(coordinate, "point").doc());
    }

    @Test
    void indexedFaceSetKeepsXj3dDeclarationOrder() {
        Spec.Node ifs = node("IndexedFaceSet");
        assertEquals("Geometry", ifs.component());
        assertEquals(1, ifs.level());
        // Not alphabetical: this is the order Xj3D's `fieldDecl[...]` slots are filled in, which
        // is what makes a diff against Base*.java readable. The SFNode references come first, then
        // the flags, then the four set_* eventIns the parser accepts, then the index fields.
        assertEquals(List.of(
                "coord:SFNode:exposedField",
                "texCoord:SFNode:exposedField",
                "color:SFNode:exposedField",
                "normal:SFNode:exposedField",
                "fogCoord:SFNode:exposedField",
                "attrib:SFNode:exposedField",
                "solid:SFBool:field",
                "convex:SFBool:field",
                "ccw:SFBool:field",
                "creaseAngle:SFFloat:field",
                "colorPerVertex:SFBool:field",
                "normalPerVertex:SFBool:field",
                "set_normalIndex:MFInt32:eventIn",
                "set_coordIndex:MFInt32:eventIn",
                "set_colorIndex:MFInt32:eventIn",
                "set_texCoordIndex:MFInt32:eventIn",
                "normalIndex:MFInt32:field",
                "coordIndex:MFInt32:field",
                "colorIndex:MFInt32:field",
                "texCoordIndex:MFInt32:field"), shape(ifs));
        assertEquals("NULL", field(ifs, "coord").defaultValue());
        assertEquals("true", field(ifs, "ccw").defaultValue());
        // UOM's own spelling, kept verbatim: it writes 0 here and 0.0 for Text.maxExtent.
        assertEquals("0", field(ifs, "creaseAngle").defaultValue());
        assertEquals("", field(ifs, "coordIndex").defaultValue());
    }

    @Test
    void textCarriesStringAndANestedFontStyle() {
        Spec.Node text = node("Text");
        assertEquals("Text", text.component());
        assertEquals(1, text.level());
        assertEquals(List.of(
                "string:MFString:exposedField",
                "fontStyle:SFNode:exposedField",
                "length:MFFloat:exposedField",
                "maxExtent:SFFloat:exposedField",
                "solid:SFBool:field"), shape(text));
        assertEquals("0.0", field(text, "maxExtent").defaultValue());
        assertEquals(List.of("FontStyle"), field(text, "fontStyle").childNodes());
        // VRML97's Text is hollow by default, which is a fact only Xj3D's declaration order and
        // UOM's default can give together.
        assertEquals("false", field(text, "solid").defaultValue());
    }

    @Test
    void nodeHoldingFieldsKnowWhichNodesMayGoThere() {
        Spec.Node ifs = node("IndexedFaceSet");
        assertEquals(List.of("Coordinate"), field(ifs, "coord").childNodes());
        // UOM lists this one as "X3DSingleTextureCoordinateNode|MultiTextureCoordinate"; the '|'
        // is a separator, and reading it as one name used to leave this list empty.
        assertEquals(List.of("TextureCoordinate"), field(ifs, "texCoord").childNodes());
        assertFalse(field(ifs, "solid").holdsNodes(), "only the two node types hold nodes");
        assertTrue(field(ifs, "coord").holdsNodes());
    }

    @Test
    void childrenAcceptGeometryAndNestThemselves() {
        List<String> children = field(node("LOD"), "children").childNodes();
        for (String expected : List.of("Shape", "Transform", "Billboard", "Switch", "Inline",
                "ProximitySensor", "WorldInfo", "Script", "Box", "Sphere", "Text",
                "IndexedFaceSet")) {
            assertTrue(children.contains(expected), "children should be able to hold " + expected);
        }
        // UOM's X3DChildNode members are not enough, because UOM describes X3D 4: it moved geometry
        // inside Shape and re-parented X3DGeometryNode off X3DChildNode, so expanding the abstract
        // type alone drops every geometry node - and `children [ Box { } ]` is legal VRML97. The
        // count is pinned so that a future change to that correction has to be a decision.
        assertEquals(45, children.size(), children.toString());
        // A grouping node inside its own children is the commonest nesting there is; ten corpus
        // files write `children [ Transform { } ]`, so the list has to offer it.
        assertTrue(children.contains("LOD"), "children should nest");
        for (String refused : List.of("Coordinate", "Normal", "Color", "Appearance", "Material",
                "FontStyle", "TextureCoordinate")) {
            assertFalse(children.contains(refused), refused + " is not a child node");
        }
    }

    @Test
    void theVrml97NamesX3dRenamedStillResolve() {
        // LOD.level and Switch.choice are legal VRML97 and exist in Xj3D only as `fieldMap`
        // entries pointing at `children`. Without them the server would flag correct files.
        Spec.Node lod = node("LOD");
        Spec.Field children = field(lod, "children");
        assertEquals(List.of("level"), children.aliases());
        assertEquals(children, lod.field("level").orElse(null));
        assertEquals("MFNode", lod.field("level").orElseThrow().type());
        Spec.Node sw = node("Switch");
        assertEquals("children", sw.field("choice").orElseThrow().name());
        assertTrue(sw.field("whichChoice").isPresent(), "Switch's own field, of course");
    }

    @Test
    void anUnknownNodeIsUnknownRatherThanMissing() {
        assertTrue(spec.hasNode("IndexedFaceSet"));
        assertFalse(spec.hasNode("Geometry2D"), "an X3D 4.x node must not look like a typo we"
                + " simply did not load");
        assertFalse(spec.hasNode("text"), "VRML97 node names are case-sensitive");
        assertEquals(List.of(), node("Coordinate").field("points").stream().toList(),
                "one letter off is no field, or the diagnostic for a wrong name never fires");
    }

    @Test
    void theTwentyOneFieldTypesCarryTheirValueWidths() {
        assertEquals(21, spec.types().size(), "11 SF plus 10 MF types; SFImage has no MF form");
        assertEquals(3, spec.type("SFVec3f").orElseThrow().width());
        assertEquals(3, spec.type("MFColor").orElseThrow().width());
        assertEquals(4, spec.type("MFRotation").orElseThrow().width());
        assertEquals(1, spec.type("MFInt32").orElseThrow().width());
        assertEquals(2, spec.type("SFVec2f").orElseThrow().width());
        // The types whose one value is not a number: a width here would make M4's element count
        // check reject every legal SFImage, SFString, SFNode and SFBool.
        for (String name : List.of("SFBool", "SFImage", "SFNode", "SFString", "MFBool", "MFNode",
                "MFString")) {
            assertEquals(0, spec.type(name).orElseThrow().width(), name);
        }
        assertTrue(spec.type("MFImage").isEmpty(), "there is no MFImage in VRML97");
        assertTrue(spec.type("").isEmpty());
    }

    @Test
    void aSnippetIsOfferedForEveryType() {
        for (Spec.ValueType type : spec.types()) {
            assertFalse(type.snippet().isEmpty(), type.name() + " needs something to insert");
            // MF values are written one element per line in the corpus and in the plan's example.
            if (type.name().startsWith("MF")) {
                assertTrue(type.snippet().contains(",\n"), type.name() + " " + type.snippet());
            }
        }
    }

    @Test
    void aSchemaThisBuildCannotReadIsRefusedOutLoud() {
        String future = """
                {"version": "2", "valueTemplates": {}, "nodes": []}""";
        IllegalStateException e = assertThrowsIllegalState(future);
        assertTrue(e.getMessage().contains("version"), e.getMessage());
        // A file that parses but says nothing is still version 1, and empty is legal: it is the
        // missing `version` that is the danger.
        assertThrowsIllegalState("{\"valueTemplates\": {}, \"nodes\": []}");
        assertTrue(Spec.read("""
                {"version": "1", "valueTemplates": {}, "nodes": []}""").nodes().isEmpty());
    }

    private static IllegalStateException assertThrowsIllegalState(String json) {
        try {
            Spec.read(json);
        } catch (IllegalStateException e) {
            return e;
        }
        throw new AssertionError("expected Spec.read to refuse: " + json);
    }

    private static Spec.Field field(Spec.Node node, String name) {
        Spec.Field found = node.field(name).orElse(null);
        assertTrue(found != null, node.name() + " has no field " + name + "; it has "
                + shape(node));
        return found;
    }
}
